DB_TIMEOUT=30
DB_IDLE_CONN_TIMEOUT=45
DB_MAX_POOL_SIZE=8
DB_DB_NAME_PREFIX={{DB_NAME_PREFIX}}

GLOBAL_DB_CONNECTION_STR="{{DEV_DB_HOST}}/{{DEV_DB_AUTHDB}}?retryWrites=true&w=majority"

# Use for test
GLOBAL_DB_CONNECTION_PREFIX=

# should be secret:
GLOBAL_DB_USERNAME={{DEV_DB_USER}}
GLOBAL_DB_PASSWORD={{DEV_DB_PASSWORD}}

# Listening Ports for all services
LOGGING_SERVICE_LISTEN_PORT={{LOGGING_SERVICE_LISTEN_PORT}}
USER_MANAGEMENT_LISTEN_PORT={{USER_MANAGEMENT_LISTEN_PORT}}
STUDY_SERVICE_LISTEN_PORT={{STUDY_SERVICE_LISTEN_PORT}}
MESSAGING_SERVICE_LISTEN_PORT={{MESSAGING_SERVICE_LISTEN_PORT}}
EMAIL_CLIENT_SERVICE_LISTEN_PORT={{EMAIL_CLIENT_SERVICE_LISTEN_PORT}}
GATEWAY_LISTEN_PORT={{GATEWAY_LISTEN_PORT}}
MANAGEMENT_API_GATEWAY_LISTEN_PORT={{MANAGEMENT_API_GATEWAY_LISTEN_PORT}}

# User
ADDR_MESSAGING_SERVICE={{DEV_DB_HOST}}:{{MESSAGING_SERVICE_LISTEN_PORT}}
ADDR_LOGGING_SERVICE={{LOGGING_SERVICE_HOST}}:{{LOGGING_SERVICE_LISTEN_PORT}}
ADDR_USER_MANAGEMENT_SERVICE={{DEV_DB_HOST}}:{{USER_MANAGEMENT_LISTEN_PORT}}
ADDR_STUDY_SERVICE={{DEV_DB_HOST}}:{{STUDY_SERVICE_LISTEN_PORT}}
ADDR_EMAIL_CLIENT_SERVICE={{DEV_DB_HOST}}:{{EMAIL_CLIENT_SERVICE_LISTEN_PORT}}

CORS_ALLOW_ORIGINS=http://{{DEV_DB_HOST}}

WEB_CLIENT_HOST={{WEB_CLIENT_HOST}}